### ISSUE TITLE
Uncaught exception of type St12out_of_range

### ISSUE THREAD

**Issue by wookietreiber** [infphilo/tophat#42]
Here is the command that is run:

```
tophat -p 7 --fusion-search -o SecondTry FusedReference M_05_66.1 M_05_66.2
```

Here is the output:

```
        Warning: --fusion-search with Bowtie2 may not work well as it may require much memory space and produce many spurious fusions.  Please try --bowtie1 option if this doesn't work.

[2016-09-22 13:43:46] Beginning TopHat run (v2.1.1)
-----------------------------------------------
[2016-09-22 13:43:46] Checking for Bowtie
                  Bowtie version:        2.2.9.0
[2016-09-22 13:43:46] Checking for Bowtie index files (genome)..
[2016-09-22 13:43:46] Checking for reference FASTA file
        Warning: Could not find FASTA file /data/wkdv/app-tests/jenkins-tophat-mapping-recombination/FusedReference.fa
[2016-09-22 13:43:46] Reconstituting reference FASTA file from Bowtie index
  Executing: /usr/local/bowtie2/2.2.9-1/bin/bowtie2-inspect /data/wkdv/app-tests/jenkins-tophat-mapping-recombination/FusedReference > SecondTry/tmp/FusedReference.fa
[2016-09-22 13:43:46] Generating SAM header for /data/wkdv/app-tests/jenkins-tophat-mapping-recombination/FusedReference
[2016-09-22 13:43:46] Preparing reads
         left reads: min. length=126, max. length=126, 16921245 kept reads (80502 discarded)
        right reads: min. length=126, max. length=126, 16918512 kept reads (83235 discarded)
[2016-09-22 13:54:15] Mapping left_kept_reads to genome FusedReference with Bowtie2 
[2016-09-22 14:10:02] Mapping left_kept_reads_seg1 to genome FusedReference with Bowtie2 (1/5)
[2016-09-22 14:11:21] Mapping left_kept_reads_seg2 to genome FusedReference with Bowtie2 (2/5)
[2016-09-22 14:12:39] Mapping left_kept_reads_seg3 to genome FusedReference with Bowtie2 (3/5)
[2016-09-22 14:14:03] Mapping left_kept_reads_seg4 to genome FusedReference with Bowtie2 (4/5)
[2016-09-22 14:15:32] Mapping left_kept_reads_seg5 to genome FusedReference with Bowtie2 (5/5)
[2016-09-22 14:17:17] Mapping right_kept_reads to genome FusedReference with Bowtie2 
[2016-09-22 14:33:11] Mapping right_kept_reads_seg1 to genome FusedReference with Bowtie2 (1/5)
[2016-09-22 14:34:29] Mapping right_kept_reads_seg2 to genome FusedReference with Bowtie2 (2/5)
[2016-09-22 14:35:48] Mapping right_kept_reads_seg3 to genome FusedReference with Bowtie2 (3/5)
[2016-09-22 14:37:08] Mapping right_kept_reads_seg4 to genome FusedReference with Bowtie2 (4/5)
[2016-09-22 14:38:30] Mapping right_kept_reads_seg5 to genome FusedReference with Bowtie2 (5/5)
[2016-09-22 14:40:07] Searching for junctions via segment mapping
[2016-09-22 14:42:09] Retrieving sequences for splices
[2016-09-22 14:42:09] Indexing splices
Building a SMALL index
[2016-09-22 14:42:10] Mapping left_kept_reads_seg1 to genome segment_juncs with Bowtie2 (1/5)
[2016-09-22 14:45:54] Mapping left_kept_reads_seg2 to genome segment_juncs with Bowtie2 (2/5)
[2016-09-22 14:49:21] Mapping left_kept_reads_seg3 to genome segment_juncs with Bowtie2 (3/5)
[2016-09-22 14:52:31] Mapping left_kept_reads_seg4 to genome segment_juncs with Bowtie2 (4/5)
[2016-09-22 14:55:52] Mapping left_kept_reads_seg5 to genome segment_juncs with Bowtie2 (5/5)
[2016-09-22 15:00:21] Joining segment hits
[2016-09-22 15:05:57] Mapping right_kept_reads_seg1 to genome segment_juncs with Bowtie2 (1/5)
[2016-09-22 15:09:43] Mapping right_kept_reads_seg2 to genome segment_juncs with Bowtie2 (2/5)
[2016-09-22 15:13:21] Mapping right_kept_reads_seg3 to genome segment_juncs with Bowtie2 (3/5)
[2016-09-22 15:16:41] Mapping right_kept_reads_seg4 to genome segment_juncs with Bowtie2 (4/5)
[2016-09-22 15:20:12] Mapping right_kept_reads_seg5 to genome segment_juncs with Bowtie2 (5/5)
[2016-09-22 15:24:46] Joining segment hits
[2016-09-22 15:29:56] Reporting output tracks
        [FAILED]
Error running /gpfs0/global/local/tophat/2.1.1-1/bin/tophat_reports --min-anchor 8 --splice-mismatches 0 --min-report-intron 50 --max-report-intron 500000 --min-isoform-fraction 0.15 --output-dir SecondTry/ --max-multihits 20 --max-seg-multihits 40 --segment-length 25 --segment-mismatches 2 --min-closure-exon 100 --min-closure-intron 50 --max-closure-intron 5000 --min-coverage-intron 50 --max-coverage-intron 20000 --min-segment-intron 50 --max-segment-intron 500000 --read-mismatches 2 --read-gap-length 2 --read-edit-dist 2 --read-realign-edit-dist 3 --max-insertion-length 3 --max-deletion-length 3 --fusion-search --fusion-anchor-length 20 --fusion-min-dist 10000000 --fusion-read-mismatches 2 --fusion-multireads 2 --fusion-multipairs 2 -z gzip -p7 --inner-dist-mean 50 --inner-dist-std-dev 20 --no-closure-search --no-coverage-search --no-microexon-search --sam-header SecondTry/tmp/FusedReference_genome.bwt.samheader.sam --report-discordant-pair-alignments --report-mixed-alignments --samtools=/gpfs0/global/local/tophat/2.1.1-1/bin/samtools_0.1.18 --bowtie2-max-penalty 6 --bowtie2-min-penalty 2 --bowtie2-penalty-for-N 1 --bowtie2-read-gap-open 5 --bowtie2-read-gap-cont 3 --bowtie2-ref-gap-open 5 --bowtie2-ref-gap-cont 3 SecondTry/tmp/FusedReference.fa SecondTry/junctions.bed SecondTry/insertions.bed SecondTry/deletions.bed SecondTry/fusions.out SecondTry/tmp/accepted_hits SecondTry/tmp/left_kept_reads.mapped.bam,SecondTry/tmp/left_kept_reads.candidates SecondTry/tmp/left_kept_reads.bam SecondTry/tmp/right_kept_reads.mapped.bam,SecondTry/tmp/right_kept_reads.candidates SecondTry/tmp/right_kept_reads.bam
./SeqAn-1.4.2/seqan/basic/basic_exception.h:236 FAILED!  (Uncaught exception of type St12out_of_range: basic_string::substr: __pos (which is 40) > this->size() (which is 0))
```

I got this information from the core dump:

```
$ file core.40969 
core.40969: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from '/gpfs0/global/local/tophat/2.1.1-1/bin/tophat_reports --min-anchor 8 --splice-m', real uid: 42050, effective uid: 42050, real gid: 2200, effective gid: 2200, execfn: '/gpfs0/global/local/tophat/2.1.1-1/bin/tophat_reports', platform: 'x86_64'

$ gdb $(which tophat_reports) core.40969  
...
Core was generated by `/gpfs0/global/local/tophat/2.1.1-1/bin/tophat_reports --min-anchor 8 --splice-m'.
Program terminated with signal 6, Aborted.
...
(gdb) bt
#0  0x00002b746ce8c625 in killpg () from /lib64/libc.so.6
#1  0x00002b746ce8de05 in abort () from /lib64/libc.so.6
#2  0x0000000000439564 in fail () at ./SeqAn-1.4.2/seqan/basic/debug_test_system.h:1773
#3  seqan::globalExceptionHandler () at ./SeqAn-1.4.2/seqan/basic/basic_exception.h:236
#4  0x00000000004acdd6 in __cxxabiv1::__terminate(void (*)()) () at ../../.././libstdc++-v3/libsupc++/eh_terminate.cc:47
#5  0x00000000004ace21 in std::terminate() () at ../../.././libstdc++-v3/libsupc++/eh_terminate.cc:57
#6  0x00000000004acd78 in __cxa_throw () at ../../.././libstdc++-v3/libsupc++/eh_throw.cc:87
#7  0x0000000000515915 in std::__throw_out_of_range_fmt(char const*, ...) () at ../../../.././libstdc++-v3/src/c++11/functexcept.cc:104
#8  0x000000000048079e in _M_check (bh=..., fusions=Unhandled dwarf expression opcode 0xf3) at /gpfs0/global/local/gcc/5.2.0-1/include/c++/5.2.0/bits/basic_string.h:261
#9  substr (bh=..., fusions=Unhandled dwarf expression opcode 0xf3) at /gpfs0/global/local/gcc/5.2.0-1/include/c++/5.2.0/bits/basic_string.h:2294
#10 fusions_from_alignment (bh=..., fusions=Unhandled dwarf expression opcode 0xf3) at fusions.cpp:261
#11 0x00000000004399c7 in update_fusions (hits=..., rt=..., fusions=..., fusions_ref=...) at tophat_reports.cpp:1175
#12 0x00000000004519f5 in ReportWorker::write_singleton_alignments (this=0xecb8b8, curr_obs_order=Unhandled dwarf expression opcode 0xf3) at tophat_reports.cpp:2313
#13 0x000000000045490a in ReportWorker::operator() (this=0xecb8b8) at tophat_reports.cpp:2400
#14 0x00002b746c5564fa in thread_proxy () from /usr/local/boost/1.58.0-1/lib/libboost_thread.so.1.58.0
#15 0x00002b746cc43a51 in start_thread () from /lib64/libpthread.so.0
#16 0x00002b746cf4296d in __init_misc () from /lib64/libc.so.6
#17 0x0000000000000000 in ?? ()
```

--- 

Please let me know if I can be of any further assistance in fixing this issue.

**Comment by malcook** [comment]
FWIW: this issue has been reported [elsewhere](https://groups.google.com/d/msg/tuxedo-tools-users/7v5L9LLpOIA/unilskOXBwAJ) too

**Comment by boegel** [comment]
Seems like one way to dance around this is to just downgrade to TopHat 2.1.0, cfr. https://www.biostars.org/p/186979/
