### ISSUE TITLE
Tophat Fusion Post error

### ISSUE THREAD

**Issue by pbpayal** [infphilo/tophat#52]
tophat-fusion-post -p 8 --num-fusion-reads 1 --num-fusion-pairs 2 --num-fusion-both 5 indexes/hg38

I have directory structure:
Tophat_DIr
--blast
--indexes
--tophatoutputsample
                 --accepted_hits.bam
                 --align_summary.txt
                 --deletions.bed
                 --fusions.out
                 --insertions.out
                 --junctions.bed
                 --logs
                 --prep_reads.info
                 --unmapped.bam
--ensGene.txt
--refGene.txt
Beginning TopHat-Fusion post-processing run (v2.1.0)
-----------------------------------------------
[Mon Feb 26 14:32:42 2018] Extracting 23-mer around fusions and mapping them using Bowtie
[Mon Feb 26 14:32:46 2018] Filtering fusions
Traceback (most recent call last):
  File "/usr/local/bin/tophat-fusion-post", line 2924, in <module>
    sys.exit(main())
  File "/usr/local/bin/tophat-fusion-post", line 2895, in main
    filter_fusion(bwt_idx_prefix, params)
  File "/usr/local/bin/tophat-fusion-post", line 965, in filter_fusion
    ensGene_list = read_genes("ensGene.txt")
  File "/usr/local/bin/tophat-fusion-post", line 917, in read_genes
    num_exons = int(line[7])
ValueError: invalid literal for int() with base 10: 'exonCount'

**Comment by matq007** [comment]
Have you tried this #45? Removed the error for me, but I'm not getting any fusions. I think it's a parameter issue for me.
